version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: pip
    directory: "/01-runtime"
    schedule:
      interval: weekly
    groups:
      runtime-development:
        dependency-type: development
        patterns:
          - "*"
